webhook:
- name: "local spinnaker"
  type: "spinnaker"
  endPoint: "http://192.168.8.22:30200/webhooks/webhook/test"
  registries:
    dockerRegistry:
      - endpoint: "wonderland-laptop.com"
        username: "admin"
        password: "Harbor12345"
        insecure-registry: false
        images:
          - "test/busybox"
          - "test/nginx"
#    aws: []